stage: develop-pipeline # Stage Name
awsRegion: us-west-1
awsRegionShortName: ca #two or three letter abbreviation for the region. You can choose your own abbreviation
rootUserEmailParamStorePath: '/rsw/develop-pipeline/rootUser/email' # Log into your AWS account and store root user email in SSM Param store
allowedOrigins: ['http://localhost:3000', 'http://localhost:3002'] # SWB API will allow this domains to make requests.
cognitoDomain: 'rsw-develop-pipeline' # Must be globally unique

vpcId: ''
albSubnetIds: []
ecsSubnetIds: []

# internet-facing ALB
# If you want internet-facing put value `true` else `false`
albInternetFacing: true

# Auditing
fieldsToMaskWhenAuditing: ['user', 'password', 'accessKey', 'code', 'codeVerifier']
