#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Git Secrets Action
description: runs git-secrets scan

runs:
  using: "composite"
  steps:
    - name: Run Git Secrets
      shell: bash
      run: node common/scripts/install-run-rush.js git-secrets-scan

    - name: Print remediation message
      shell: bash
      if: failure()
      run: echo "git secrets found potential leaked credentials. If ANY credentials were committed, they MUST be immediately revoked."