#stage: dev # Stage Name
#apiBaseUrl: https://<api>.us-east-1.amazonaws.com
#awsRegion: us-east-1
#awsRegionShortName: va #two or three letter abbreviation for the region. You can choose your own abbreviation

