version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # For debugging purposes
      - ls -al
      - npm --version
      - node --version
      # Install dependencies
      - npm install -g aws-cdk
  pre_build:
    commands:
      - echo "Installing dependencies and executing unit tests " `pwd`
      - npm install -g @microsoft/rush
      - rush install && rush build && rush test
      - echo "Installing dependencies and executing unit tests completed on " `date`
  build:
    commands:
      - node common/scripts/install-run-rushx.js compile
      - STAGE=testEnv node common/scripts/install-run-rushx.js cdk synth
      - echo "Starting build " `date` `pwd`
      - chmod +x ./deployment/build-s3-dist.sh && ./deployment/build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
      - echo "Build completed " `date`
      - echo "Starting open-source-dist " `date` `pwd`
      - chmod +x ./deployment/build-open-source-dist.sh && ./deployment/build-open-source-dist.sh $SOLUTION_NAME
      - echo "Open Source Dist completed " `date`
  post_build:
    commands:
      - echo "Retrieving next stage buildspec " `date` `pwd`
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on " `date`

artifacts:
  files:
    - '**/*'
    - deployment/**/*
    - source/**/*
    - .gitignore
    - sonar-project.properties
    - CHANGELOG.md
    - buildspec.yml