#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Slack Notification
description: Action to send slack notification on failure
inputs:
  slack_webhook_url:
    description: "Slack WebHook URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Slack Notification
      shell: bash
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":" -> \n[ \n\tSTATUS: \"${{ job.status }}\" \n\tWORKFLOW_NAME: \"${{ github.workflow }}\" \n\tJOB: \"${{ github.job }}\" \n\tJOB_URL: \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\" \n] "}' ${{ inputs.slack_webhook_url }}