## Note:
## Please deploy the swb-reference package before running the integration test suite.
## Settings declared here are merged with the main accounts CFN outputs to create integration test config items

# Default Env Config for launching a new environment
envTypeId: 'et-prod-a6zllrbwwkhae,pa-hsqxcyewq6b4y'
envTypeConfigId: 'etc-3c0a9969-de21-4992-b263-64c1ddfda7e2'
projectId: 'proj-77565f8d-35bd-4978-ada8-4530eda24a26'
envType: 'sagemakerNotebook'

#Cognito Integ Test Client
rootUserNameParamStorePath: '/swb/release-candidate-private/rootUser/email'
rootPasswordParamStorePath: '/swb/release-candidate-private/rootUser/password'

projectAdmin1UserNameParamStorePath: '/swb/release-candidate-private/pa1/email'
projectAdmin1PasswordParamStorePath: '/swb/release-candidate-private/pa1/password'

projectAdmin2UserNameParamStorePath: '/swb/release-candidate-private/pa2/email'
projectAdmin2PasswordParamStorePath: '/swb/release-candidate-private/pa2/password'

researcher1UserNameParamStorePath: '/swb/release-candidate-private/researcher1/email'
researcher1PasswordParamStorePath: '/swb/release-candidate-private/researcher1/password'

## Default external ID
externalIdPath: '/rsw/release-candidate-private/externalId'

## Default Hosting Account
defaultHostingAccountId: 'acc-00448659-13e5-4181-8691-0fb98d42446e'

## Hosting account used for Account Creation tests
hostAwsAccountIdParamStorePath: '/swb/release-candidate-private/accountsTest/awsAccountId'
hostingAccountHandlerRoleArnParamStorePath: '/swb/release-candidate-private/accountsTest/hostingAccountHandlerRoleArn'
envMgmtRoleArnParamStorePath: '/swb/release-candidate-private/accountsTest/envMgmtRoleArn'
encryptionKeyArnParamStorePath: '/swb/release-candidate-private/accountsTest/encryptionKeyArn'
