AdminUser: ''
AdminPassword: ''
EnvTypes: [{ EnvironmentType: 'Sagemaker Jupyter Notebook', EnvironmentTypeConfig: 'Config 1' }] ##Environment Types to test
EnvProject: 'Test Project' ##default environment project to be selected when creating an environment
EnvStudies: [] ##default environment studies to be selected when creating an environment
CleanEnvironments: true
