#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#
name: Build-and-test
on: ['pull_request']

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
          token: ${{ secrets.MERGE_TOKEN }}

      - name: Base Action
        uses: ./.github/actions/baseAction
      
      - name: Rush test and update the README file in each package with the coverage badge
        run: node common/scripts/install-run-rush.js test --verbose

      - name: Cfn-nag Action
        uses: ./.github/actions/cfnNagAction

      - name: Git-secrets Action
        uses: ./.github/actions/gitSecretsAction

      - name: Viperlight Action
        uses: ./.github/actions/viperlightAction

          

