#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Build-and-test
on: ['pull_request']

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.MERGE_TOKEN }}

      - name: Base Action
        uses: ./.github/actions/baseAction

      - name: Rush test
        run: node common/scripts/install-run-rush.js test:only --verbose

      - name: Generates common coverage summary reports for all packages in ./coverage dir
        run: node common/scripts/install-run-rush.js common-coverage-report

      - name: Generate Codecov for @aws/workbench-core-accounts
        uses: codecov/codecov-action@v3
        with:
          files: workbench-core/accounts/temp/coverage/coverage-final.json
          flags: workbench-core-accounts

      - name: Generate Codecov for @aws/workbench-core-accounts-ui
        uses: codecov/codecov-action@v3
        with:
          files: workbench-core/accounts-ui/temp/coverage/coverage-final.json
          flags: workbench-core-accounts-ui

      - name: Generate common Codecov for Root
        uses: codecov/codecov-action@v3
        with:
          files: coverage/coverage-final.json
          flags: root
