#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Build-and-test
on: ['pull_request']

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
          token: ${{ secrets.MERGE_TOKEN }}
      
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"

      - name: echo commit message 
        run: echo "${{ steps.last-commit-message.outputs.msg }}"

      - name: Base Action
        if: steps.last-commit-message.outputs.msg != 'README.md updates by github-actions[bot]'
        uses: ./.github/actions/baseAction
      
      - name: Rush test and update the README file in each package with the coverage badge
        if: steps.last-commit-message.outputs.msg != 'README.md updates by github-actions[bot]'
        run: node common/scripts/install-run-rush.js test --verbose

      - name: cfn-nag Action
        if: steps.last-commit-message.outputs.msg != 'README.md updates by github-actions[bot]'
        uses: ./.github/actions/cfnNagAction

      - name: Update root README file with common coverage badge
        if: steps.last-commit-message.outputs.msg != 'README.md updates by github-actions[bot]'
        run: node common/scripts/install-run-rush.js common-coverage-make-badge
      
      - name: Update package info in root README file
        if: steps.last-commit-message.outputs.msg != 'README.md updates by github-actions[bot]'
        run: |
          cd workbench-core/repo-scripts/repo-toolbox
          node ../../../common/scripts/install-run-rushx.js readme -v || exit_status=$?
          if [[ $exit_status != 0 ]]; then
            node ../../../common/scripts/install-run-rushx.js readme
          fi

      - name: echo modified files
        if: steps.last-commit-message.outputs.msg != 'README.md updates by github-actions[bot]'
        run: git status

      - name: Auto commit updated README files
        if: steps.last-commit-message.outputs.msg != 'README.md updates by github-actions[bot]'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "README.md updates by github-actions[bot]"
          commit_options: '--no-verify'
          file_pattern: "README.md **/README.md"

