#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Build-and-test
on: ['pull_request']

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}

      - name: Base Action
        uses: ./.github/actions/baseAction
      
      - name: Rush test
        run: node common/scripts/install-run-rush.js test --verbose

      # - name: Code Coverage badge check
      #   run: node common/scripts/install-run-rush.js make-badges --ci

      - name: Generate Common Coverage
        run: node common/scripts/install-run-rush.js common-coverage-report
      
      - name: Update package info in root README file
        run: |
          cd workbench-core/repo-scripts/repo-toolbox
          node ../../../common/scripts/install-run-rushx.js readme -v || exit_status=$?
          if [[ $exit_status != 0 ]]; then
            node ../../../common/scripts/install-run-rushx.js readme
          fi
      
      - name: Auto commit README files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: README.md updates
          file_pattern: "**/README.md"
      
      # - name: Common Code Coverage badge check
      #   run: node common/scripts/install-run-rush.js common-coverage --ci

