#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Build-and-test
on: ['pull_request']

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Base Action
        uses: ./.github/actions/baseAction
      
      - name: Rush test
        run: node common/scripts/install-run-rush.js test:only --verbose

      - name: Code Coverage badge check
        run: node common/scripts/install-run-rush.js make-badges --ci
      
      - name: Common Code Coverage badge check
        run: node common/scripts/install-run-rush.js common-coverage-ci