#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Build-and-test
on: 
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
          token: ${{ secrets.MERGE_TOKEN }}
      
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"

      - name: echo last commit message
        run: echo "${{ steps.last-commit-message.outputs.msg }}"

      - name: Base Action
        if: "!contains(${{ steps.last-commit-message.outputs.msg }}, 'github-actions[bot]')"
        uses: ./.github/actions/baseAction
      
      - name: Rush test
        if: "!contains(${{ steps.last-commit-message.outputs.msg }}, 'github-actions[bot]')"
        run: node common/scripts/install-run-rush.js test --verbose

      # - name: Code Coverage badge check
      #   run: node common/scripts/install-run-rush.js make-badges --ci

      - name: Generate Common Coverage
        if: "!contains(${{ steps.last-commit-message.outputs.msg }}, 'github-actions[bot]')"
        run: node common/scripts/install-run-rush.js common-coverage-report
      
      - name: Update package info in root README file
        if: "!contains(${{ steps.last-commit-message.outputs.msg }}, 'github-actions[bot]')"
        run: |
          cd workbench-core/repo-scripts/repo-toolbox
          node ../../../common/scripts/install-run-rushx.js readme -v || exit_status=$?
          if [[ $exit_status != 0 ]]; then
            node ../../../common/scripts/install-run-rushx.js readme
          fi

      # - name: Get last commit sha
      #   id: last-commit-sha
      #   run: |
      #     echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Auto commit README files
        if: "!contains(${{ steps.last-commit-message.outputs.msg }}, 'github-actions[bot]')"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "doc: README.md updates by github-actions[bot]"
          commit_options: '--no-verify'
          # push_options: '--force'
          # skip_fetch: true
          file_pattern: "README.md **/README.md"
      
      # - name: Common Code Coverage badge check
      #   run: node common/scripts/install-run-rush.js common-coverage --ci

