#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Build-and-test
on: ['pull_request']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'

      # - name: Cache Rush
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       common/temp/install-run
      #       ~/.rush
      #     key: ${{ runner.os }}-rush-${{ hashFiles('rush.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-rush-
      #       ${{ runner.os }}-

      # - name: Cache pnpm
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       common/temp/pnpm-store
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-
      #       ${{ runner.os }}-

      - name: Install dependecies
        run: node common/scripts/install-run-rush.js install
      
      - name: Rush check
        run: node common/scripts/install-run-rush.js check

      - name: Rush build
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Rush test
        run: node common/scripts/install-run-rush.js test:only --verbose

      - name: Code Coverage badge check
        run: node common/scripts/install-run-rush.js make-badges --ci