#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Cfn-nag-scan
on: ['pull_request']

jobs:
  cfn-nag-scan:
    name: Run cfn-nag scan
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Base Action
        uses: ./.github/actions/baseAction

      - name: cdk synth swb-reference
        env:
          STAGE: testEnv
        run: |
          cd solutions/swb-reference
          node ../../common/scripts/install-run-rushx.js compile
          node ../../common/scripts/install-run-rushx.js cdk synth

      - name: cdk synth swb-ui
        env:
          STAGE: testEnv
          SYNTH_REGION_SHORTNAME: va
          SYNTH_REGION: us-east-1
        run: |
          cd solutions/swb-ui/infrastructure
          node ../../../common/scripts/install-run-rushx.js cdk synth

      - name: cdk synth example
        run: |
          cd workbench-core/example/infrastructure
          node ../../../common/scripts/install-run-rushx.js compile
          node ../../../common/scripts/install-run-rushx.js cdk synth

      - name: cdk synth github-oidc
        run: |
          cd workbench-core/repo-scripts/github-oidc
          node ../../../common/scripts/install-run-rushx.js cdk synth

      - name: Run cfn-nag on all .template.json files
        uses: stelligent/cfn_nag@master
        with:
          input_path: .
          extra_args: --fail-on-warnings --template-pattern .template.json -g
          output_path: cfn_nag_json.out

      - name: Run cfn-nag on all .cfn.yaml files
        uses: stelligent/cfn_nag@master
        with:
          input_path: .
          extra_args: --fail-on-warnings --template-pattern .cfn.yaml -g
          output_path: cfn_nag_yaml.out

      - name: Grep cfn-nag for violations
        uses: sergeysova/jq-action@v2
        id: cfn-nag
        # No. of violations: warnings + errors
        with:
          cmd: |
            cat cfn_nag_json.out cfn_nag_yaml.out > cfn_nag.out
            grep -E '^(Failures|Warnings)' cfn_nag.out | awk '{ SUM += $3} END { print SUM }'

      - name: echo violation count
        run: echo ${{ steps.cfn-nag.outputs.value }}

      # - name: Fail if violations detected in cfn-nag
      #   run: exit ${{ steps.cfn-nag.outputs.value }}