#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: deploy-and-integration-test-example
on:
  workflow_call:
    secrets: 
      aws-region:
        required: true
      role-to-assume:
        required: true
      aws-dev-account-region:
        required: true

jobs:
# deploy only when files specific to swb package changed
  deploy-example:
    runs-on: ubuntu-20.04
    environment: dev
    permissions:
      id-token: write
      contents: read
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      # - name: Get specific changed files for example package
      #   id: changed-example-package-files
      #   uses: tj-actions/changed-files@v18.7
      #   with:
      #     files: |
      #       workbench-core/audit/*
      #       workbench-core/logging/**/*
      #       workbench-core/example/**/*
      #       !README.md

      - name: Cache Rush
        # if: steps.changed-swb-files.outputs.any_changed == 'true'
        uses: actions/cache@v3
        with:
          path: |
            common/temp/install-run
            ~/.rush
          key: ${{ runner.os }}-rush-${{ hashFiles('rush.json') }}
          restore-keys: |
            ${{ runner.os }}-rush-
            ${{ runner.os }}-

      - name: Cache pnpm
        # if: steps.changed-swb-files.outputs.any_changed == 'true'
        uses: actions/cache@v3
        with:
          path: |
            common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
            ${{ runner.os }}-

      - name: Install dependecies
        # if: steps.changed-swb-files.outputs.any_changed == 'true'
        run: node common/scripts/install-run-rush.js install

      - name: Rush build
        # if: steps.changed-swb-files.outputs.any_changed == 'true'
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Configure AWS Credentials
        # if: steps.changed-swb-files.outputs.any_changed == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.aws-region }}
          role-to-assume: ${{ secrets.role-to-assume }}
          role-session-name: OIDCSessionName

      - name: Deploy example package to Dev
        # if: steps.changed-example-package-files.outputs.any_changed == 'true'
        id: endpoint
        run: |
          cd workbench-core/example/infrastructure
          node ../../../common/scripts/install-run-rushx.js cdk bootstrap ${{ secrets.aws-dev-account-region }} -v
          node ../../../common/scripts/install-run-rushx.js cdk:deploy
          SERVICE_ENDPOINT=`jq ".InfrastructureStack.HttpEndpoint" cdk-outputs.json | tr -d '"'`
          echo "::set-output name=SERVICE_ENDPOINT::$SERVICE_ENDPOINT"
      
      - name: Example package integration test
        # if: steps.changed-example-package-files.outputs.any_changed == 'true'
        env: 
          SERVICE_ENDPOINT: "${{ steps.endpoint.outputs.SERVICE_ENDPOINT }}"
        run: |
          echo "$SERVICE_ENDPOINT"
          cd workbench-core/example/infrastructure
          node ../../../common/scripts/install-run-rushx.js test:integration --verbose

  
