#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Deploy-and-integration-test-example-app
on: ['pull_request']
# on:
#   workflow_call:
#     secrets:
#       aws-test-region:
#         required: true
#       role-to-assume:
#         required: true
#       aws-test-account-region:
#         required: true

jobs:
  deploy-and-integration-test-example:
    runs-on: ubuntu-20.04
    environment: test
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Base Action
        uses: ./.github/actions/baseAction

      - name: Configure AWS Credentials
        # if: steps.changed-swb-files.outputs.any_changed == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.aws-test-region }}
          role-to-assume: ${{ secrets.test-role-to-assume }}
          role-session-name: TestOIDCSessionName

      - name: Deploy example package to Test environment
        run: |
          cd workbench-core/example/infrastructure
          node ../../../common/scripts/install-run-rushx.js cdk bootstrap ${{ secrets.aws-test-account-region }} -v
          node ../../../common/scripts/install-run-rushx.js cdk:deploy

      - name: Example package integration test
        run: |
          cd workbench-core/example/infrastructure
          node ../../../common/scripts/install-run-rushx.js integration-tests --verbose