name: Deploy to Dev and Integration Test
on:
  push:
    branches:
      - develop

jobs:
  deploy-integration:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      # - name: Cache Rush
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       common/temp/install-run
      #       ~/.rush
      #     key: ${{ runner.os }}-rush-${{ hashFiles('rush.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-rush-
      #       ${{ runner.os }}-

      # - name: Cache pnpm
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       common/temp/pnpm-store
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-
      #       ${{ runner.os }}-

      # - name: Install dependecies
      #   run: node common/scripts/install-run-rush.js install

      # - name: Build
      #   run: node common/scripts/install-run-rush.js build --verbose
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEV_REGION }}
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          role-session-name: OIDCSessionName
      
      - name: Deploy SWB-Reference to Dev
        run: |
          node common/scripts/install-run-rush.js install
          node common/scripts/install-run-rush.js build --verbose
          cd solutions/swb-reference
          node ../../common/scripts/install-run-rushx.js compile
          STAGE='dev' node ../../common/scripts/install-run-rushx.js cdk bootstrap ${{ secrets.AWS_DEV_ACCOUNT_REGION }} -v
          STAGE='dev' node ../../common/scripts/install-run-rushx.js cdk-deploy --all --require-approval never
          STAGE='dev' node ../../common/scripts/install-run-rushx.js run-postDeployment
