name: Deploy to Dev and Integration Test
on:
  push:
    branches:
      - testdevelop

jobs:
  deploy-integration:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Cache Rush
        uses: actions/cache@v3
        with:
          path: |
            common/temp/install-run
            ~/.rush
          key: ${{ runner.os }}-rush-${{ hashFiles('rush.json') }}
          restore-keys: |
            ${{ runner.os }}-rush-
            ${{ runner.os }}-

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: |
            common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
            ${{ runner.os }}-

      - name: Install dependecies
        run: node common/scripts/install-run-rush.js install

      - name: Build
        run: node common/scripts/install-run-rush.js build --verbose
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEV_REGION }}
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          role-session-name: OIDCSessionName
      
      - name: Deploy POC Infrastructure to Dev
        run: |
          node common/scripts/install-run-rush.js cdk:bootstrap -e ${{ secrets.AWS_DEV_ACCOUNT_REGION }} -o @amzn/workbench-core-infrastructure
          node common/scripts/install-run-rush.js cdk -d
          node common/scripts/install-run-rush.js cdk:deploy
      # - name: Deploy POC Infrastructure to Dev - cd workbench-core/infrastructure
      #   run: cd workbench-core/infrastructure

      # - name: Deploy POC Infrastructure to Dev - cdk bootstrap
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     working_dir: workbench-core/infrastructure
      #     cdk_subcommand: 'bootstrap ${{ secrets.AWS_DEV_ACCOUNT_REGION }}'
      
      # - name: Deploy POC Infrastructure to Dev - cdk diff
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     working_dir: workbench-core/infrastructure
      #     cdk_subcommand: 'diff'

      # - name: Deploy POC Infrastructure to Dev - cdk deploy
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     working_dir: workbench-core/infrastructure
      #     cdk_subcommand: 'deploy'
      #     cdk_args: '--all --require-approval'

      # - name: Deploy POC Infrastructure to Dev - cdk diff
      #     cdk diff
      #     cdk deploy --all --require-approval never --outputs-file cdk-outputs.json
      #     echo "SERVICE_ENDPOINT=`jq ".InfrastructureStack.HttpEndpoint" cdk-outputs.json | tr -d '"'`" > $CI_PROJECT_DIR/deploy.env
