name: dummy
on: ['pull_request']

jobs:
  pre-dummy:
    name: pre-dummy
    runs-on: ubuntu-20.04
    steps:
      - name: echo
        run: |
          echo "pre-dummy"
  dummy:
    name: dummy
    runs-on: ubuntu-20.04
    needs: [deploy-and-integration-test-swb-reference, deploy-and-integration-test-example]
    steps:
      - name: echo
        run: |
          echo "dummy"