name: dummy
on:
  pull_request:

jobs:
  deploy-example:
    uses: awslabs/monorepo-for-service-workbench/.github/workflows/deploy-integration-example.yml@feature/example-logging-auditing
    secrets:
      aws-dev-region: ${{ secrets.AWS_DEV_REGION }}
      role-to-assume: ${{ secrets.ASSUME_ROLE }}
      aws-dev-account-region: ${{ secrets.AWS_DEV_ACCOUNT_REGION }}
      cognito-username: "${{ secrets.COGNITO_USERNAME }}"
      cognito-password: "${{ secrets.COGNITO_PASSWORD }}"
      cognito-client-id: "${{ secrets.COGNITO_CLIENT_ID }}"

  dummy:
    name: dummy
    runs-on: ubuntu-20.04
    needs: [deploy-example]
    steps:
      - name: echo
        run: |
          echo "dummy"