name: merge-develop-to-main
on:
  pull_request:
  push:
    branches:
      - develop
  
jobs:
  merge-develop-to-main:
    name: Merge develop to main
    runs-on: ubuntu-20.04
    needs: [deploy-and-integration-test-swb-reference, deploy-and-integration-test-example]
    steps:
      - name: echo
        run: |
          echo "dummy"