name: End-to-end tests
on: ['pull_request']
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: workbench-core/example/infrastructure
          config: baseUrl="https://example-app-domain-155208731242-us-east-1.auth.us-east-1.amazoncognito.com/login?client_id=5l3lr5v12gbk0ollb2sc7c0o8r&response_type=code&scope=openid&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F"