name: GitHub-release
on: workflow_dispatch

jobs:
  github-release:
    runs-on: ubuntu-20.04
    name: Trigger release 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        
    - name: Create a Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
      