name: release integration tests

on:
  push:
    branches:
      - 'release/4debe38e-5796-47b6-96ec-881a87e0df21'


jobs:
  pre-deployment-check:
    name: Pre deployment check
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: "Block Concurrent Deployments"
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-example-app:
    needs: [pre-deployment-check]
    uses: ./.github/workflows/deploy-integration-example-app.yml
    with:
      environment: release
    secrets:
      aws-region: ${{ secrets.AWS_RELEASE_REGION }}
      role-to-assume: ${{ secrets.RELEASE_ASSUME_ROLE }}
      aws-account-region: ${{ secrets.AWS_EXAMPLE_APP_RELEASE_ACCOUNT_REGION }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
  deploy-swb-reference:
    needs: [pre-deployment-check]
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/deploy-integration-swb-reference.yml@develop
    with:
      environment: release-swb
    secrets:
      aws-dev-region: ${{ secrets.AWS_DEV_REGION }}
      role-to-assume: ${{ secrets.ASSUME_ROLE }}
      aws-dev-account-region: ${{ secrets.AWS_DEV_ACCOUNT_REGION }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
      CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID_RELEASE }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME_RELEASE }}

  deploy-swb-demo:
    needs: [deploy-swb-reference]
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/deploy-swb-reference-demo.yml@develop
    with:
      environment: release-swb    
    secrets:
      role-to-assume: ${{ secrets.ASSUME_ROLE }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID_RELEASE }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME_RELEASE }}