name: release integration tests

on:
  push:
    branches:
      - 'testRelease/rc1'


jobs:
  pre-deployment-check:
    name: Pre deployment check
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: "Block Concurrent Deployments"
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-example-app:
    needs: [pre-deployment-check]
    uses: ./.github/workflows/deploy-integration-example-app.yml
    with:
      environment: release
    secrets:
      aws-region: ${{ secrets.AWS_RELEASE_REGION }}
      role-to-assume: ${{ secrets.RELEASE_ASSUME_ROLE }}
      aws-account-region: ${{ secrets.AWS_EXAMPLE_APP_RELEASE_ACCOUNT_REGION }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
  deploy-swb-reference:
    needs: [pre-deployment-check]
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/deploy-integration-swb-reference.yml@develop
    with:
      environment: release-swb
      stage: release-candidate
    secrets:
      aws-dev-region: ${{ secrets.AWS_DEV_REGION }}
      role-to-assume: ${{ secrets.ASSUME_ROLE }}
      aws-dev-account-region: ${{ secrets.AWS_DEV_ACCOUNT_REGION }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
      CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID_RELEASE }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME_RELEASE }}
  deploy-swb-reference-byon:
    needs: [pre-deployment-check]
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/deploy-integration-swb-reference-byon.yml@develop
    with:
      environment: release-swb-byon
      stage: release-candidate-private
    secrets:
      aws-dev-region: ${{ secrets.AWS_RELEASE_REGION_BYON }}
      role-to-assume: ${{ secrets.ASSUME_ROLE }}
      aws-dev-account-region: ${{ secrets.AWS_RELEASE_ACCOUNT_REGION_BYON }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD_BYON }}
      CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER_BYON }}
      COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN_BYON }}
      USER_POOL_ID: ${{ secrets.USER_POOL_ID_BYON }}
      CLIENT_ID: ${{ secrets.CLIENT_ID_BYON }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_BYON }}
      VPC_ID: ${{ secrets.VPC_ID_BYON }}
      ALB_SUBNET_1: ${{ secrets.ALB_SUBNET_1_BYON }}
      ALB_SUBNET_2: ${{ secrets.ALB_SUBNET_2_BYON }}
      ECS_SUBNET_1: ${{ secrets.ECS_SUBNET_1_BYON }}
      ECS_SUBNET_2: ${{ secrets.ECS_SUBNET_2_BYON }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID_BYON }}

  slack-notification:
    name: Merge develop to stage
    runs-on: ubuntu-20.04
    needs: [deploy-swb-reference, deploy-swb-reference-byon, deploy-example-app]
    steps:
      - name: Slack Failure Notification
        if: failure()
        uses: ./.github/actions/notification
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}