name: release integration tests

on:
  push:
    branches:
      - 'testRelease/integTests'


jobs:
  pre-deployment-check:
    name: Pre deployment check
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: "Block Concurrent Deployments"
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-example-app:
    needs: [pre-deployment-check]
    uses: ./.github/workflows/deploy-integration-example-app.yml
    secrets:
      aws-region: ${{ secrets.AWS_RELEASE_REGION }}
      role-to-assume: ${{ secrets.RELEASE_ASSUME_ROLE }}
      aws-account-region: ${{ secrets.AWS_EXAMPLE_APP_RELEASE_ACCOUNT_REGION }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      environment: release
