name: "Lint PR"

on:
  pull_request_target:
    types: [opened, synchronize, edited, reopened]
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  lint-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}