name: "Lint-pr"

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  lint-pr:
    name: Validate PR title
    runs-on: ubuntu-20.04
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Echo Context
        if: always()
        run: echo "${{ toJson(github) }}"

      - name: Slack Message
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failure ${{ job.status }} ${{ github.workflow }}"}' ${{ secrets.SLACK_WEBHOOK }}


      # - uses: ravsamhq/notify-slack-action@v2
      #   if: failure()
      #   with:
      #     status: ${{ job.status }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.TEST_SLACK }}