name: merge-release-to-develop-notification

on:
  push:
    branches:
      - 'release/*'

jobs:
  merge-release-to-develop-notification:
    runs-on: ubuntu-20.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          fetch-depth: 0

      - name: Merge release to develop
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"A new PR with COMMIT_ID: ${{ github.sha }} has been merged to \"release\" branch. Please create a PR to merge the changes back to \"develop\" branch"}' ${{ inputs.slack_webhook_url }}