name: merge-release-to-develop

on:
  push:
    branches:
      - 'release/*'

jobs:
  readme-commit:
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/readme-commit.yml@${{ github.ref_name }}
    with:
      branch: ${{ github.ref_name }}
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      passphrase: ${{ secrets.PASSPHRASE }}
      merge-token: ${{ secrets.MERGE_TOKEN }}
      bot-user: ${{ secrets.BOT_USER }}
      bot-user-email: ${{ secrets.BOT_USER_EMAIL }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
  merge-release-to-develop:
    needs: [readme-commit]
    runs-on: ubuntu-20.04
    env:
      COMMIT_HASH: "${{ needs.readme-commit.outputs.commit_hash }}"
      CHANGES_DETECTED: "${{ needs.readme-commit.outputs.changes_detected }}"
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          fetch-depth: 0
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set git config
        run: |
          git config user.email ${{ secrets.BOT-USER-EMAIL }}
          git config user.name ${{ secrets.BOT-USER }}
          git config commit.gpgsign true

      # There's no way for github actions to push to a protected branch. This is a workaround
      # See https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/30
      - name: Temporarily disable branch protection on develop
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: aws-solutions
          repo: solution-spark-on-aws
          branch: develop
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: enable merge commits
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}
          owner: aws-solutions
          repo: solution-spark-on-aws
          allow_merge_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: Merge to develop
        run: |
          echo "Set the COMMIT_ID to merge to develop, to current workflow commit id, if no readme commit was made"
          echo "Else"
          echo "Set the COMMIT_ID to README commit id"
          COMMIT_ID=''
          if $CHANGES_DETECTED; then
            COMMIT_ID=$COMMIT_HASH
          else
            COMMIT_ID=$GITHUB_SHA
          fi
          git checkout develop
          echo
          echo "  Attempting to merge the '${{ github.ref_name }}' branch ($COMMIT_ID)"
          echo "  into the 'develop' branch ($(git log -1 --pretty=%H develop))"
          echo
          git merge $COMMIT_ID --ff-only --no-edit
          git push origin develop

      - name: disable merge commits
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}
          owner: aws-solutions
          repo: solution-spark-on-aws
          allow_merge_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: Enable branch protection on develop
        uses: octokit/request-action@v2.x
        if: always() # Make sure to enable branch protection even if other steps fail
        with:
          route: POST /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: aws-solutions
          repo: solution-spark-on-aws
          branch: develop
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
