#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Merge-to-testDevelop
on:
  pull_request_target:
    types:
      - closed
    branches:
      - testDevelop
  
jobs:
  readme-commit:
    if: github.event.pull_request.merged == true
    uses: awslabs/monorepo-for-service-workbench/.github/workflows/readme-commit.yml@testDevelop
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      passphrase: ${{ secrets.PASSPHRASE }}
      merge-token: ${{ secrets.MERGE_TOKEN }}
      bot-user: ${{ secrets.BOT_USER }}
      bot-user-email: ${{ secrets.BOT_USER_EMAIL }}
      
  # deploy-swb-reference:
  #   needs: [readme-commit]
  #   uses: awslabs/monorepo-for-service-workbench/.github/workflows/deploy-integration-swb-reference.yml@develop
  #   secrets:
  #     aws-dev-region: ${{ secrets.AWS_DEV_REGION }}
  #     role-to-assume: ${{ secrets.ASSUME_ROLE }}
  #     aws-dev-account-region: ${{ secrets.AWS_DEV_ACCOUNT_REGION }}
  
  deploy-example:
    needs: [readme-commit]
    uses: awslabs/monorepo-for-service-workbench/.github/workflows/deploy-integration-example.yml@testDevelop
    secrets:
      aws-dev-region: ${{ secrets.AWS_DEV_REGION }}
      role-to-assume: ${{ secrets.ASSUME_ROLE }}
      aws-dev-account-region: ${{ secrets.AWS_DEV_ACCOUNT_REGION }}
      cognito-username: "${{ secrets.COGNITO_USERNAME }}"
      cognito-password: "${{ secrets.COGNITO_PASSWORD }}"
      cognito-client-id: "${{ secrets.COGNITO_CLIENT_ID }}"

  echo-readme-commit-id:
    name: echo-readme-commit-id
    runs-on: ubuntu-20.04
    needs: [readme-commit]
    env: 
      COMMIT_HASH: "${{ needs.readme-commit.outputs.commit_hash }}"
      CHANGES_DETECTED: "${{ needs.readme-commit.outputs.changes_detected }}"
    steps:
      - name: echo commit id
        run: |
          echo $CHANGES_DETECTED
          echo $COMMIT_HASH
    
  # merge-develop-to-main:
  #   name: Merge develop to main
  #   runs-on: ubuntu-20.04
  #   needs: [deploy-example]

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.MERGE_TOKEN }}
  #         fetch-depth: 0
  #     # There's no way for github actions to push to a protected branch. This is a workaround
  #     # See https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/30
  #     - name: Temporarily disable branch protection
  #       uses: octokit/request-action@v2.x
  #       with:
  #         route: DELETE /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
  #         owner: awslabs
  #         repo: monorepo-for-service-workbench
  #         branch: main
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

  #     - name: Merge to main
  #       run: |
  #         git checkout main
  #         echo
  #         echo "  Attempting to merge the 'develop' branch ($(git log -1 --pretty=%H develop))"
  #         echo "  into the 'main' branch ($(git log -1 --pretty=%H main))"
  #         echo
  #         git merge --ff-only --no-edit develop
  #         git push origin main
          
  #     - name: Enable branch protection
  #       uses: octokit/request-action@v2.x
  #       if: always() # Make sure to enable branch protection even if other steps fail
  #       with:
  #         route: POST /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
  #         owner: awslabs
  #         repo: monorepo-for-service-workbench
  #         branch: main
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}