#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Merge-to-testDevelop
on:
  pull_request_target:
    types:
      - closed
    branches:
      - testDevelop
  
jobs:
  commit-sha:
    runs-on: ubuntu-20.04
    # needs: [verify-commit-msg]
    steps:
      - name: commit-sha
        run: echo $GITHUB_SHA

  readme-commit:
    if: github.event.pull_request.merged == true
    uses: awslabs/monorepo-for-service-workbench/.github/workflows/readme-commit.yml@testDevelop
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      passphrase: ${{ secrets.PASSPHRASE }}
      merge-token: ${{ secrets.MERGE_TOKEN }}
      bot-user: ${{ secrets.BOT_USER }}
      bot-user-email: ${{ secrets.BOT_USER_EMAIL }}
      
  # deploy-swb-reference:
  #   needs: [readme-commit]
  #   uses: awslabs/monorepo-for-service-workbench/.github/workflows/deploy-integration-swb-reference.yml@develop
  #   secrets:
  #     aws-dev-region: ${{ secrets.AWS_DEV_REGION }}
  #     role-to-assume: ${{ secrets.ASSUME_ROLE }}
  #     aws-dev-account-region: ${{ secrets.AWS_DEV_ACCOUNT_REGION }}
  
  deploy-example:
    uses: awslabs/monorepo-for-service-workbench/.github/workflows/deploy-integration-example.yml@testDevelop
    secrets:
      aws-dev-region: ${{ secrets.AWS_DEV_REGION }}
      role-to-assume: ${{ secrets.ASSUME_ROLE }}
      aws-dev-account-region: ${{ secrets.AWS_DEV_ACCOUNT_REGION }}
      cognito-username: "${{ secrets.COGNITO_USERNAME }}"
      cognito-password: "${{ secrets.COGNITO_PASSWORD }}"
      cognito-client-id: "${{ secrets.COGNITO_CLIENT_ID }}"

  echo-readme-commit-id:
    name: echo-readme-commit-id
    runs-on: ubuntu-20.04
    needs: [readme-commit]
    env: 
      COMMIT_HASH: "${{ needs.readme-commit.outputs.commit_hash }}"
      CHANGES_DETECTED: "${{ needs.readme-commit.outputs.changes_detected }}"
    steps:
      - name: echo commit id
        run: |
          echo $CHANGES_DETECTED
          echo $COMMIT_HASH
    
  merge-develop-to-testMain:
    name: Merge develop to TestMain
    runs-on: ubuntu-20.04
    needs: [readme-commit, deploy-example]
    env: 
      COMMIT_HASH: "${{ needs.readme-commit.outputs.commit_hash }}"
      CHANGES_DETECTED: "${{ needs.readme-commit.outputs.changes_detected }}"
      
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          fetch-depth: 0
      # There's no way for github actions to push to a protected branch. This is a workaround
      # See https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/30
      - name: Temporarily disable branch protection
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: awslabs
          repo: monorepo-for-service-workbench
          branch: testMain
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: Merge to testMain
        run: |
          COMMIT_ID=''
          if $CHANGES_DETECTED; then
            COMMIT_ID=$COMMIT_HASH
          else
            COMMIT_ID=$GITHUB_SHA
          fi
          echo "$COMMIT_ID"
          git checkout testMain
          echo
          echo "  Attempting to merge the 'testDevelop' branch ($COMMIT_ID)"
          echo "  into the 'testMain' branch ($(git log -1 --pretty=%H testMain))"
          echo
          echo $GITHUB_SHA
          echo "$COMMIT_HASH"
          echo "$CHANGES_DETECTED"
          echo "$COMMIT_ID"
          echo
          git merge $COMMIT_ID --ff-only --no-edit 
          git push origin testMain
          
      - name: Enable branch protection
        uses: octokit/request-action@v2.x
        if: always() # Make sure to enable branch protection even if other steps fail
        with:
          route: POST /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: awslabs
          repo: monorepo-for-service-workbench
          branch: testMain
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}