name: Release-tags
on:
  push:
    tags:
      - "@amzn/*_v*.*.*"

jobs:
  release-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.MERGE_TOKEN }}