#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Security Code Scanning
on:
  pull_request:
    branches:
      - develop
      - 'release/*'
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - develop
jobs:
  CodeQL-Analyze:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          config-file: ./.github/codeql/codeql-config.yml
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2