name: Solutions Pipeline Checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  solutions-pipeline-checks:
    name: Viperlight scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run viperlight scan
        run: node common/scripts/install-run-rush.js viperlight-scan