#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Stage branch protection
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
# The purpose of this workflow is to create a failing Status check on pull request against stage. This will prevent
# PR from being merged into stage.
jobs:
  stage-protection:
    name: Only create PR against develop branch, not stage branch
    runs-on: ubuntu-20.04
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: stage protection
        if: steps.branch-name.outputs.base_ref_branch == 'stage'
        run: |
          echo "PR has target branch ${{ steps.branch-name.outputs.base_ref_branch }}. Failing workflow..."
          exit 1