#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Temp-workflow-step
on: ['pull_request']

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.MERGE_TOKEN }}

      - name: Base Action
        uses: ./.github/actions/baseAction

      - name: Synth and check
        run:  |
          echo "
          vpcId: ${{ secrets.VPC_ID }}
          userPoolId: ${{ secrets.USER_POOL_ID }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          albSubnetIds: [${{ secrets.ALB_SUBNET_1 }}, ${{ secrets.ALB_SUBNET_2 }}]
          ecsSubnetIds: [${{ secrets.ECS_SUBNET_1 }}, ${{ secrets.ECS_SUBNET_2 }}]
          hostedZoneId: ${{ secrets.HOSTED_ZONE_ID }}" >> "solutions/swb-reference/src/config/swbv2-private.yaml
          cd solutions/swb-reference
          node ../../common/scripts/install-run-rushx.js compile
          STAGE='swbv2-private' node ../../common/scripts/install-run-rushx.js cdk bootstrap ${{ secrets.aws-dev-account-region }} -v
          STAGE='swbv2-private' node ../../common/scripts/install-run-rushx.js cdk synth
          STAGE='swbv2-private' node ../../common/scripts/install-run-rushx.js cdk-deploy"