# test branch deletion
name: "test branch deletion"

on:
  pull_request:
    types: [closed]
    branches: [testDevelop]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Temporarily disable branch protection on test/*
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: awslabs
          repo: solution-spark-on-aws
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: Delete test/* branch after merge
        if: always()
        run: |
          echo ${{github.event.pull_request.number}}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}

      - name: Enable branch protection on test/*
        uses: octokit/request-action@v2.x
        if: always() # Make sure to enable branch protection even if other steps fail
        with:
          route: POST /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: awslabs
          repo: solution-spark-on-aws
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
