#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: "test branch deletion"

on:
  pull_request:
    types: [closed]
    branches: [testDevelop]

jobs:
  delete-test-branch-on-merge:
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'test/')
    runs-on: ubuntu-latest
    steps:
      - name: echo branch protection
        run: |
          echo ${{ github.ref_protected }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref_name }}

      - name: Delete test/* branch protection after merge to develop
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/branches/{branch}/protection
          owner: awslabs
          repo: solution-spark-on-aws
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: Delete test/* branch after merge to develop
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: ${{ github.head_ref }}

      # - name: Enable branch protection on test/*
      #   uses: octokit/request-action@v2.x
      #   if: always() # Make sure to enable branch protection even if other steps fail
      #   with:
      #     route: POST /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
      #     owner: awslabs
      #     repo: solution-spark-on-aws
      #     branch: ${{ github.head_ref }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
