#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Test-deploy-integration
on: ['pull_request']

jobs:
  deploy-swb-reference:
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/test-deploy-integration-swb-reference.yml@pnpm-audit-rush-update
    secrets:
      aws-dev-region: ${{ secrets.AWS_DEV_REGION }}
      role-to-assume: ${{ secrets.ASSUME_ROLE }}
      aws-dev-account-region: ${{ secrets.AWS_DEV_ACCOUNT_REGION }}
      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
      CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}

  deploy-example-app:
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/test-deploy-integration-example-app.yml@pnpm-audit-rush-update
    secrets:
      aws-test-region: ${{ secrets.AWS_TEST_REGION }}
      test-role-to-assume: ${{ secrets.TEST_ASSUME_ROLE }}
      aws-test-account-region: ${{ secrets.AWS_TEST_ACCOUNT_REGION }}