name: test-protection

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  enable-test-branch-protection:
    if: contains(${{ github.head_ref }}, 'test/')
    runs-on: ubuntu-latest
    steps:
      - name: Enable branch protection on test/*
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/{owner}/{repo}/branches/{branch}/protection
          owner: awslabs
          repo: solution-spark-on-aws
          branch: ${{ github.head_ref }}
          body: ${{ toJSON(env.REQUEST_BODY) }}
        env:
          REQUEST_BODY: |
            required_status_checks: {
              strict: true
            },
            enforce_admins: true,
            dismiss_stale_reviews: true,
            require_code_owner_reviews: true,
            required_approving_review_count: 1,
            required_conversation_resolution: false
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
