#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: example-integration-test
on: ['pull_request']

jobs:
  deploy-example-app:
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/deploy-integration-example-app.yml@test-example-integration
    secrets:
      aws-test-region: ${{ secrets.AWS_TEST_REGION }}
      test-role-to-assume: ${{ secrets.TEST_ASSUME_ROLE }}
      aws-test-account-region: ${{ secrets.AWS_TEST_ACCOUNT_REGION }}
      aws-test-hosting-account-id: ${{ secrets.AWS_TEST_HOSTING_ACCOUNT_ID }}
      aws-test-hosting-account-region: ${{ secrets.AWS_TEST_HOSTING_ACCOUNT_REGION }}
      external_id: ${{ secrets.EXTERNAL_ID }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}