name: "Test"

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  test-fail-demo:
    uses: awslabs/solution-spark-on-aws/.github/workflows/test_worflow_call.yml@feature/slack-notification-fix
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
