name: test-github-oidc
on: ['pull_request']
 
jobs:
  deploy-swb-reference:
    uses: aws-solutions/solution-spark-on-aws/.github/workflows/test-deploy-parallel-integration-swb-reference.yml@parallel-integration-tests
    with:
      stage: sam
      environment: prTest
    secrets:
      aws-dev-region: ${{ secrets.SWB_PR_TEST_AWS_REGION }}
      role-to-assume: ${{ secrets.SWB_PR_ASSUME_ROLE }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
      CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}
      HOSTED_ZONE_ID: ${{ secrets.SWB_PR_HOSTED_ZONE_ID_TEST }}
      DOMAIN_NAME: ${{ secrets.SWB_PR_DOMAIN_NAME_TEST }}